# Generated by Django 5.0.7 on 2024-08-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0002_mymodel_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
