# Generated by Django 5.0.7 on 2024-08-07 07:24

import manages.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[manages.views.validate_email])),
            ],
        ),
    ]
